# Generated by Django 4.0.4 on 2022-06-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_alter_mobile_des'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile',
            name='des',
        ),
        migrations.AddField(
            model_name='mobile',
            name='RAM_des',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='mobile',
            name='cam_des',
            field=models.TextField(default='NA'),
        ),
    ]
