# Generated by Django 4.0.4 on 2022-07-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_remove_mobile_des_mobile_ram_des_mobile_cam_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='image',
            field=models.ImageField(default='cart.jpg', upload_to='mobile_pics'),
        ),
    ]
